package com.erp.Schedular;

import com.erp.Dto.Request.SalaryRequest;
import com.erp.Model.User;
import com.erp.Repository.User.UserRepository;
import com.erp.Service.SalaryService.SalaryService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.YearMonth;
import java.util.List;

@Component
@RequiredArgsConstructor
@Slf4j
public class SalaryScheduler {

    private final UserRepository userRepository;
    private final SalaryService salaryService;

    // Runs every 1st day of month at 00:05 AM
    @Scheduled(cron = "0 5 0 1 * ?")
    public void generateMonthlySalaries() {
        log.info("Running scheduled salary generation...");

        List<User> users = userRepository.findAll();

        for (User user : users) {
            try {
                double baseSalary = 30000;

                SalaryRequest request = new SalaryRequest();
                request.setUserId(user.getId());
                request.setBaseSalary(baseSalary);
                request.setMonth(YearMonth.now());
                request.setRemarks("Auto-generated by scheduler");

                salaryService.generateSalaryForMonth(request);

                log.info("Salary generated for user ID: {}", user.getId());
            } catch (Exception ex) {
                log.error("Failed to generate salary for user ID: {}", user.getId(), ex);
            }
        }
    }
}
